areas:
  - name: storefront1
    baseUrl: http://localhost:3000/sf1/
    default: true
    config:
      bigcommerce:
        authToken: ...
        storeHash: ...
        channelId: 1
        graphqlEndpoint: ...
        storefrontToken: ...
  - name: storefront2
    baseUrl: http://localhost:3000/sf2/
    config:
      bigcommerce:
        authToken: ...
        storeHash: ...
        channelId: 1
        graphqlEndpoint: ...
        storefrontToken: ...
